name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@51af9cb861670a53ad41b7abacedebdd5b07c3f9 # v0
    permissions:
      pull-requests: write
      issues: write