name: release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  update-major-version-tag:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Major Version Tag
      id: update_major_version_tag
      uses: ./update-major-version-tag
